version: "3.8"

services:
  db:
    container_name: app-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_psw
      MYSQL_USER: db_user
      MYSQL_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - ./postgre:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

volumes:
  database: